### ISSUE TITLE
TIAM Models - Section: Link To Other Models

### ISSUE THREAD

**Issue by LippkauFelix** [experimentarium/etsap-tiam#33]
What TIAM models should be mentioned in [Link To Other Models](https://etsap-tiam.readthedocs.io/en/latest/optional/link-to-other-models.html). 

I am aware of TIAM-UCL and TIAM-IER.

**Comment by olejandro** [comment]
Is this not on soft linking TIAM to other models?

**Comment by LippkauFelix** [comment]
ah good point!
