### ISSUE TITLE
Regional Coverage Section - different appearance than folder structure

### ISSUE THREAD

**Issue by LippkauFelix** [experimentarium/etsap-tiam#46]
I am a bit confused as the folder structure of the "regional coverage" section differs from the real output on the rendered site. 

For example: Region description is written but not shown:
https://github.com/experimentarium/etsap-tiam/blob/main/docs/regional_coverage/region-description.md
https://etsap-tiam.readthedocs.io/en/latest/regional_coverage/index.html

**Comment by olejandro** [comment]
Sorry, was not done yet! :-)
